/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.bandtec.javaswing2.java.swing.aula;

import java.awt.Color;
import java.util.concurrent.ThreadLocalRandom;

/**
 *
 * @author Aluno
 */
public class MonitoramentoDeDados extends javax.swing.JFrame {
    
    private int currentValueProgressBar;

    /**
     * Creates new form Tela1
     */
    public MonitoramentoDeDados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prgCPU = new javax.swing.JProgressBar();
        btnVisualizarDados = new javax.swing.JButton();
        prgDisco = new javax.swing.JProgressBar();
        prgMemo = new javax.swing.JProgressBar();
        jLabelCPU = new javax.swing.JLabel();
        jLabelDisco = new javax.swing.JLabel();
        jLabelMemo = new javax.swing.JLabel();
        lblMaxCPU = new javax.swing.JLabel();
        lblMaxDisco = new javax.swing.JLabel();
        lblMaxMemo = new javax.swing.JLabel();
        max = new javax.swing.JLabel();
        min = new javax.swing.JLabel();
        med = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblMinCPU = new javax.swing.JLabel();
        lblMinDisco = new javax.swing.JLabel();
        lblMinMemo = new javax.swing.JLabel();
        lblMedCPU = new javax.swing.JLabel();
        lblmedDisco = new javax.swing.JLabel();
        medMemo = new javax.swing.JLabel();
        alerta = new javax.swing.JLabel();
        lblAlertaCPU = new javax.swing.JLabel();
        lblAlertaDisco = new javax.swing.JLabel();
        lblAlertaMemo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        prgCPU.setStringPainted(true);

        btnVisualizarDados.setText("Visualizar Dados");
        btnVisualizarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarDadosActionPerformed(evt);
            }
        });

        prgDisco.setStringPainted(true);

        prgMemo.setStringPainted(true);

        jLabelCPU.setText("CPU");

        jLabelDisco.setText("Disco");

        jLabelMemo.setText("Memória");

        lblMaxCPU.setText("0");

        lblMaxDisco.setText("0");

        lblMaxMemo.setText("0");

        max.setText("MAX");

        min.setText("MIN");

        med.setText("MÉDIA");

        jLabel1.setText("CPU");

        jLabel2.setText("DISCO");

        jLabel3.setText("MEMÓRIA");

        lblMinCPU.setText("0");

        lblMinDisco.setText("0");

        lblMinMemo.setText("0");

        lblMedCPU.setText("0");

        lblmedDisco.setText("0");

        medMemo.setText("0");

        alerta.setText("ALERTA");

        lblAlertaCPU.setText("ESTAVEL");

        lblAlertaDisco.setText("ESTAVEL");

        lblAlertaMemo.setText("ESTAVEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(alerta, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(max, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(med, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblMinCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblMaxCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lblMedCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(lblAlertaCPU)))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblAlertaDisco)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(lblMinDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(0, 6, Short.MAX_VALUE))
                                                .addComponent(lblMaxDisco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblmedDisco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblMinMemo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblMaxMemo)
                                            .addComponent(medMemo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(54, 54, 54)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAlertaMemo)
                                            .addComponent(jLabel3))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(prgCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(122, 122, 122))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(prgDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(prgMemo, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(49, 49, 49)))
                                    .addComponent(btnVisualizarDados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(219, 219, 219))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelMemo)
                                        .addGap(218, 218, 218))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelCPU)
                                        .addGap(229, 229, 229)))
                                .addGap(0, 41, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelCPU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prgCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDisco)
                .addGap(2, 2, 2)
                .addComponent(prgDisco, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabelMemo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prgMemo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnVisualizarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(max)
                    .addComponent(lblMaxCPU)
                    .addComponent(lblMaxDisco)
                    .addComponent(lblMaxMemo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(min)
                    .addComponent(lblMinCPU)
                    .addComponent(lblMinDisco)
                    .addComponent(lblMinMemo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(med)
                    .addComponent(lblMedCPU)
                    .addComponent(lblmedDisco)
                    .addComponent(medMemo))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alerta)
                    .addComponent(lblAlertaCPU)
                    .addComponent(lblAlertaDisco)
                    .addComponent(lblAlertaMemo))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Integer contador = 0;
    Integer maxCPU = 0;
    Integer maxDisco = 0;
    Integer maxMemo = 0;
    
    Integer minCPU = 100;
    Integer minDisco = 100;
    Integer minMemo = 100;
    
    Integer mediaCPU = 0;
    Integer mediaDisco = 0;
    Integer mediaMemo = 0;
    
    Integer somaCPU = 0;
    Integer somaDisco = 0;
    Integer somaMemo = 0;
    private void btnVisualizarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarDadosActionPerformed
      
     contador++;
      
     Integer dadosCPU = ThreadLocalRandom.current().nextInt(0,101);
     Integer dadosDisco = ThreadLocalRandom.current().nextInt(0,101);
     Integer dadosMemo = ThreadLocalRandom.current().nextInt(0,101);
      
      prgCPU.setValue(dadosCPU);
      prgDisco.setValue(dadosDisco);
      prgMemo.setValue(dadosMemo);
     
      //CALCULO DA MEDIA DOS DADOS
      somaCPU += dadosCPU;
      somaDisco += dadosDisco;
      somaMemo += dadosMemo;
     
      mediaCPU = somaCPU / contador;
      mediaDisco = somaDisco / contador;
      mediaMemo = somaMemo / contador;
           
      lblMedCPU.setText(mediaCPU.toString());
      lblmedDisco.setText(mediaDisco.toString());
      medMemo.setText(mediaMemo.toString());
      
      
      //MAX E MIN DOS DADOS
        //CPU
        if(dadosCPU > maxCPU){
           maxCPU = dadosCPU;
           lblMaxCPU.setText(maxCPU.toString());
           
        }
        
        if(dadosCPU < minCPU) {
            minCPU = dadosCPU;
            lblMinCPU.setText(minCPU.toString());
        }
        
        //DISCO
        if (dadosDisco > maxDisco) {
            maxDisco = dadosDisco;
            lblMaxDisco.setText(maxDisco.toString());
        }
        
        if(dadosDisco < minDisco){
            minDisco = dadosDisco;
            lblMinDisco.setText(minDisco.toString());
        }

        //MEMORIA
        if (dadosMemo > maxMemo) {
            maxMemo = dadosMemo;
            lblMaxMemo.setText(maxMemo.toString());
        }
        
        if(dadosMemo < minMemo) {
            minMemo = dadosMemo;
            lblMinMemo.setText(minMemo.toString());
        }
        
        
        
       //ALERTAS
        alerta.setForeground(Color.RED); 
        
         //CPU
        if(dadosCPU <= 60) {
            lblAlertaCPU.setText("ESTAVEL");
            lblAlertaCPU.setForeground(Color.BLUE);
        }
        else if(dadosCPU > 60 && dadosCPU <= 80){
            lblAlertaCPU.setText("CRITICO");
            lblAlertaCPU.setForeground(Color.MAGENTA);
        } else {
            lblAlertaCPU.setText("EXT. CRITICO");
            lblAlertaCPU.setForeground(Color.RED);
        }

        //DISCOS
        if(dadosDisco <= 60) {
            lblAlertaDisco.setText("ESTAVEL");
            lblAlertaDisco.setForeground(Color.BLUE);
        }
        else if (dadosDisco > 60 && dadosDisco <= 80) {
            lblAlertaDisco.setText("CRITICO");
            lblAlertaDisco.setForeground(Color.MAGENTA);
        } else {
            lblAlertaDisco.setText("EXT. CRITICO");
            lblAlertaDisco.setForeground(Color.RED);
        }
        
        //MEMORIA
        if (dadosMemo <= 60) {
            lblAlertaMemo.setText("ESTAVEL");
            lblAlertaMemo.setForeground(Color.BLUE);
        } 
        else if (dadosMemo > 60 && dadosMemo <= 80) {
            lblAlertaMemo.setText("CRITICO");
            lblAlertaMemo.setForeground(Color.MAGENTA);
        } else {
            lblAlertaMemo.setText("EXT. CRITICO");
            lblAlertaMemo.setForeground(Color.RED);
        }
        
    }//GEN-LAST:event_btnVisualizarDadosActionPerformed

 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MonitoramentoDeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MonitoramentoDeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MonitoramentoDeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MonitoramentoDeDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MonitoramentoDeDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alerta;
    private javax.swing.JButton btnVisualizarDados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCPU;
    private javax.swing.JLabel jLabelDisco;
    private javax.swing.JLabel jLabelMemo;
    private javax.swing.JLabel lblAlertaCPU;
    private javax.swing.JLabel lblAlertaDisco;
    private javax.swing.JLabel lblAlertaMemo;
    private javax.swing.JLabel lblMaxCPU;
    private javax.swing.JLabel lblMaxDisco;
    private javax.swing.JLabel lblMaxMemo;
    private javax.swing.JLabel lblMedCPU;
    private javax.swing.JLabel lblMinCPU;
    private javax.swing.JLabel lblMinDisco;
    private javax.swing.JLabel lblMinMemo;
    private javax.swing.JLabel lblmedDisco;
    private javax.swing.JLabel max;
    private javax.swing.JLabel med;
    private javax.swing.JLabel medMemo;
    private javax.swing.JLabel min;
    private javax.swing.JProgressBar prgCPU;
    private javax.swing.JProgressBar prgDisco;
    private javax.swing.JProgressBar prgMemo;
    // End of variables declaration//GEN-END:variables
}
